---
- hosts: all
  roles:
    - role: geerlingguy.java # ansible-galaxy install geerlingguy.java
      java_packages:
        - openjdk-8-jdk
    - role: gantsign.maven # ansible-galaxy install gantsign.maven
      maven_version: '3.3.9'
    - role: node #local
    - role: geerlingguy.docker # ansible-galaxy install geerlingguy.docker