---
- name: Ensure make is installed
  apt: pkg=make state=latest

- name: Ensure git is installed
  apt: pkg=git-core state=latest

- name: Download n
  git: repo=https://github.com/visionmedia/n dest=/tmp/n

- name: Install n
  command: make -C /tmp/n

- name: Install node
  command: n stable
