---
- name: Ensure repository key is installed
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: Ensure docker registry is available
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: Ensure docker and dependencies are installed
  apt: name=docker-engine update_cache=yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.13.0/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Restart docker daemon service
  service:
    name: docker
    state: restarted
